@startuml activity_diagram_reserve
title アクティビティ図 - 部屋を予約する(UC1)

|利用者|
start
:宿泊日・客室タイプを指定する;
|システム|
if (該当する空室がある?) then (no)
  :「空室なし」を利用者に通知する;
  stop
endif
repeat
  :該当する空室一覧を提示する;
  |利用者|
  if (気に入った客室がある?) then (no)
    :宿泊日・客室タイプを変更する;
  endif
  |システム|
repeat while (客室が未選択?) is (yes)
->no;
|利用者|
:客室を選択する;
|システム|
:予約を登録する;
:予約番号を発行する;
:予約番号を利用者に提示する;
|利用者|
:予約番号を受け取る;
stop

@enduml
